import Head from "next/head";
import Image from "next/image";
import {
  Grid,
  Button,
  Container,
  Card,
  CardContent,
  Typography,
} from "@mui/material";
import styles from "../styles/Index.module.css";
import CoffeeIcon from "@mui/icons-material/Coffee";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container fixed className={styles.container}>
          <Grid container spacing={2}>
            <Grid item xs={6}>
              <Card sx={{ minWidth: 275 }}>
                <CardContent
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                  }}
                >
                  <Typography
                    sx={{ fontSize: 14, marginBottom: 3 }}
                    color="text.secondary"
                    gutterBottom
                  >
                    Loyalty Card
                  </Typography>
                  <Grid container spacing={2}>
                    {Array.from(Array(10)).map((_, index) => (
                      <Grid item xs={5} sm={4} md={4} key={index}>
                        <CoffeeIcon sx={{ height: "40px", width: "40px" }} />
                      </Grid>
                    ))}
                  </Grid>
                </CardContent>
              </Card>
              <Button variant="contained">Connect Wallet</Button>
            </Grid>
          </Grid>
        </Container>
      </main>
    </>
  );
}
